### ISSUE TITLE
Question about worklist when output is not equal to the old one in the worklist algorithm

### ISSUE THREAD

**Issue by chengfulin** [Swatinem/analyses#2]
Hello,
I cannot understand the code at line 54 of the file [lib/index.js](https://github.com/Swatinem/analyses/blob/master/lib/index.js).
I have tried something like this, two arrays, push each element of one to another on [JSBin](http://jsbin.com/xehudaqozu/1/watch?js,console) and the result <strong><em>isn't</em></strong> I expected till I changed the callback of forEach to<code>
function (val) {
    list.push(val);
}
</code>
Could you tell me did I misunderstand this line of code?
Thanks.

Sincerely yours,
ChengFu

**Comment by Swatinem** [comment]
Hm, you are absolutely right. `forEach` provides the callback with 3 arguments, and all 3 are added to the array.
TBH, I seriously don’t know why it has not been an issue so far, haha.

**Comment by Swatinem** [comment]
But yes, you could provide a PR to fix this. :-)

**Comment by chengfulin** [comment]
It seems that because <code>Array.prototype.push()</code> can have variable parameters, all arguments passed through the callback of <code>forEach</code> would become parameters of <code>push()</code>.

**Comment by Swatinem** [comment]
Exactly. Now that we have ES6 arrow functions, it shouldnt be a problem anymore.
Ideally, we could switch to a preprocessor like babel and also include a collections shim, like core-js, to have usable `Map` and `Set` types. But I’m not sure its worth the effort.
