### ISSUE TITLE
Tests failed due to Type Error of non-existing method

### ISSUE THREAD

**Issue by chengfulin** [Swatinem/analyses#4]
Hello,
when I run the existing test with <code>mocha --harmony</code>, there is an error message appeared three times, shown as follow: <code>
     TypeError: Object #&lt;Assertion&gt; has no method 'includeEql'
</code>
All of them are occurred in test/availableexpressions.js.[(1)](https://github.com/Swatinem/analyses/blob/master/test/availableexpressions.js#L36)[(2)](https://github.com/Swatinem/analyses/blob/master/test/availableexpressions.js#L45)[(3)](https://github.com/Swatinem/analyses/blob/master/test/availableexpressions.js#L36)

Is this due to the different version of <code>should</code> module?

Sincerely yours,
ChengFu

**Comment by Swatinem** [comment]
Oh, I pulled your changes in before seeing this issue.

Yes, the `should` dependency is not semver pinned, so it will pull in breaking changes.
