### ISSUE TITLE
Output of work-list algorithm

### ISSUE THREAD

**Issue by chengfulin** [Swatinem/analyses#5]
Hi,
today I realize that the output of the work-list algorithm implemented in this framework, didn't output what I expected.
For example, the available expressions algorithm, it would output <code>AvailOut(n)</code> sets not <code>Avail(n)</code> sets.
Where the algorithm is 
```
Avail(n) = ∩x ∈ pred(n) AvailOut(x)
AvailOut(n) = (GEN(n) ∪ (Avail(n) - KILL(n)))
```
Although I am using this framework to fulfill another algorithm Reaching Definitions.
Which algorithm is
```
Reach(n) = ∪x ∈ pred(n) ReachOut(x)
ReachOut(n) = (GEN(n) ∪ (Reach(n) - KILL(n)))
```
when I tested again, I found that it seems that I would get <code>ReachOut(n)</code> not <code>Reach(n)</code>

Could I just modify it a little like this:
```javascript
    var output = new Map();
	var inputs = new Map();
	while (list.length) {
		var node = list.shift();
		var pre = predecessors(node)
			.map(function (n) { return output.get(n); });
		var input = pre.length ? merge(pre) : start;
		inputs.set(node, input);
		var oldOutput = output.get(node);
		var out = transferFunction.call(node, input, list, oldOutput);
		if (!out || out instanceof Set)
			out = {output: out, enqueue: true};
		output.set(node, out.output);
		if (out.enqueue && (!oldOutput || !equals(out.output, oldOutput)))
			successors(node).forEach(function (aSuccessor) {	list.push(aSuccessor);	});
	}
	return inputs;
```

**Comment by Swatinem** [comment]
Sounds reasonable.
Lets `return {inputs, outputs}` from the function, that way users can use whatever they want.

It is a breaking change for the API though.
