### ISSUE TITLE
availableexpression says only does binary expression, what other nodes need to be walked?

### ISSUE THREAD

**Issue by roterdam** [Swatinem/analyses#7]
I'm new to this so forgive my noobness, but what other nodes do you need to analyze other than assignment expressions for the available analysis.

The comment in the code seems to suggest that more is needed to be complete, but I don't understand why.

**Comment by Swatinem** [comment]
I haven’t looked at this either in a _long_ time.
binary expressions should cover most cases. You could add logical expressions as well maybe, but it really depends on your use case
